### ISSUE TITLE
Command Injection (High Level)

### ISSUE THREAD

**Issue by ckiev5** [digininja/DVWA#508]
Hi, I can bypass the filter on command injection with High Level using a  '||'.
Here is proof:
![image](https://user-images.githubusercontent.com/32242954/182124794-414b42f7-2314-4bc3-af6f-2c45ece8cb76.png)

**Comment by digininja** [comment]
Congratulations, that is the way it is designed. If you can bypass it on impossible, then we need to fix something.

**Comment by ckiev5** [comment]
Because the symbol "||" is filtered, so I think I can not bypass with it.
Reference: [Source code](https://github.com/digininja/DVWA/blob/87c987e2804a7fb11507a4c6b66dc49958572fe5/vulnerabilities/exec/source/high.php#L11)

**Comment by digininja** [comment]
If you look at the substitutions list, the developer has messed up and put a single pipe higher in the list than the double pipe, this substitutes the first pipe you enter for an empty string but leaves the second one which works and gives you the injection.

It is a way to demonstrate that you have to thoroughly examine code if you are doing a code audit rather than just skimming over it and making assumptions.

**Comment by ckiev5** [comment]
Thank you so much for your explanation. I understood the problem.
