### ISSUE TITLE
commend injection in PING 

### ISSUE THREAD

**Issue by rootkit3421** [digininja/DVWA#618]
mkdir cmd and some cmds not working in commond injection in PING .some commonds like ls,whoami,pwd are working . please fix the issue

**Comment by digininja** [comment]
OK, give me ssh access to your box and I'll fix it.

**Comment by rootkit3421** [comment]
how i can give you ssh access to you

**Comment by digininja** [comment]
Would you really allow a stranger off the internet full access to your computer? If so, then maybe computer security isn't an area for you.

The actual reason for your problem is likely to be file system permissions. Go and learn something about those and you should be able to work out why things aren't working as you expect them to.
