### ISSUE TITLE
CSRF doesn't really make sense

### ISSUE THREAD

**Issue by duraki** [digininja/DVWA#622]
Having separate CSRF vulnerability implemented makes no sense in DVWA. Why is the whole DVWA vulnerable to CSRF anyhow? Shouldn't there be some kind of XSRF token applied in non-CSRF vulnerabilities and forms?

**Comment by digininja** [comment]
It is so that you can practice CSRF on its own as a standalone
vulnerability. It is like asking why have standalone XSS, why not put it in
the login form. I could, but then it would be harder to focus on the single
lesson.

The rest of the app isn't protected because as well as having specific
vulnerabilities in each section, the app as a whole is full of other
"hidden" issues for you to find.

**Comment by duraki** [comment]
I agree, it makes sense in this particular case. I just think that DVWA is used quite a lot "as a standard" during DAST/SAST benchmarking (and development of the similar offsec tools), therefore these produce false positives and are reported during the analysis. Nevertheless, I understand your point, just wanted to share my personal view of it. Appreciated the response, and thanks for years of development @digininja.

**Comment by digininja** [comment]
Trying to have humans trying to contend with csrf protections while also
learning about SQLi would be a bit much.

**Comment by duraki** [comment]
Haha, absolutely. Lets deffo keep it this way.
