### ISSUE TITLE
failing to launch 'already existing database'

### ISSUE THREAD

**Issue by maximlomans** [digininja/DVWA#648]
**Describe the bug**
 
kali-tweaks labs installer sets up the dvwa.db via /usr/share/dvwa/create-database-dvwa script
on second relaunch post install it fails - claiming it cant create db because it already exists. and that`s true it does exists, and the dvwa user can also login with default p@ssw0rd but question is why does it keeps recreating it ?

**Comment by digininja** [comment]
I have no idea what you are asking and I don't support scripts written by other users so if you want support for something by kali-tweaks, ask them for support.

My guess is that if you are running the create database script multiple times then it will obviously fail as it is already created. If they assume that you'd only run it once then they probably aren't handling fails gracefully.

Using unix sockets rather than a network connection is not a good idea unless you really know what you are doing with socket authentication. There is a closed ticket that covers using it but it isn't something I support because using the network connection is a much easier way to do it.
